### ISSUE TITLE
Simple Indicator Lamp

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#10]
Basically, a small circular or light.
(like the one on your radar altimeter).

**Comment by Alexustas** [comment]
I'm already done something similar

https://youtu.be/8nsPUy-EZ_g

https://youtu.be/ABhe75QEqcE

**Comment by DeputyLOL** [comment]
Where can I download this?

**Comment by Alexustas** [comment]
here: https://www.dropbox.com/s/pv94sp37izem0m9/MOARdv.zip?dl=0

prop name - ASET_SignalLamp

**Comment by DeputyLOL** [comment]
Thanks, 3 for one.
Don't know if it was intentional but you included 2 other props.
A fuel gauge and another fuel gauge!
