### ISSUE TITLE
Number displays

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#11]
Now we have dials to select numbers. We need something nice to display them on!
![autopilot](https://cloud.githubusercontent.com/assets/12616126/10367216/15f9791a-6dc7-11e5-8ef2-8fd273ecee85.jpg)
If possible, could they have the orange background and bright orange, digital style numbers?
They would also go blank when a certain variable either met or not met.

**Comment by Alexustas** [comment]
screen templates
![bandicam 2015-10-10 04-43-42-916](https://cloud.githubusercontent.com/assets/6713671/10407208/a332cc94-6f09-11e5-88f0-3a0e62594967.jpg)

**Comment by DeputyLOL** [comment]
Looks good, I spent a lot of time making my own numbers but your look better!
Can you have one more please. Glide slope angle. Goes from 1 to 25 please. Measured in degrees.

**Comment by DeputyLOL** [comment]
Some visual improvement: add a faint line where they are missing.
Basically have a faint 8 behind every number.
If you look at the heading display in the picture, you can see faint lines which would light up for other numbers.

**Comment by Alexustas** [comment]
i was thinking about that, andI will try to implement this effect. but if it involves serious complication of the model, I was not going to do it

**Comment by Alexustas** [comment]
and my skecth is not an actual representation of displays .this is done only to clarify the number of digits for each display

**Comment by DeputyLOL** [comment]
oh, we might have to change them to be more realistic in the KSP world.
If possible, altitude has 5 digits instead of 6 (will the minimums and maximums be configurable?)
Also, will colour and background colour be configurable? I want to stick to the orange, light orange style

**Comment by Alexustas** [comment]
in real life - yes 5 digits for altitude, but if someone build a kind of spaceplane ...

**Comment by DeputyLOL** [comment]
fair enough. could you make it configurable?

**Comment by Alexustas** [comment]
I will try to provide maximum flexibility to configure the display. background and characters will be a separate objects and you will be able customize colors of each object

**Comment by DeputyLOL** [comment]
cool!

**Comment by DeputyLOL** [comment]
will it be possible to toggle to different variables?

**Comment by Alexustas** [comment]
I think it would be better  to make dedicated displays 'special for MCP', the most similar (authentic) to the original display. and then do a set of displays for 'common purposes'

**Comment by DeputyLOL** [comment]
yeah I agree

**Comment by DeputyLOL** [comment]
I think that once these are done, I can make a final version of my cockpit autopilot panel.

**Comment by Alexustas** [comment]
It will take some time. so while you can use the "DigitalIndicator" as displays

**Comment by Alexustas** [comment]
I plan to use the module "JSIOdometer" to the digital displays, but I have never worked with this module and I need time to figure out all over

**Comment by DeputyLOL** [comment]
yeah, good idea. I'm going to start getting the layout of it sorted.

**Comment by Alexustas** [comment]
"JSIOdometer" module displays one variable and can be switched to the 2nd (alternative) variable. but now is not a propblem becouse we have all the power of MATH_ and SELECT_ features

**Comment by DeputyLOL** [comment]
oh yeah...

**Comment by Alexustas** [comment]
haha, "JSIOdometer" was  a bad idea ((
https://youtu.be/FO1lAGfjimE

I can not remove the effect of rotation, so... plan "B"

**Comment by Alexustas** [comment]
Yes!

https://youtu.be/ZkC5ISWdtWU

**Comment by Alexustas** [comment]
Oh yeah!
I'm really cool! :-) 

https://youtu.be/UIBr0_iT2EM

**Comment by Alexustas** [comment]
and V/SPEED stuff:

https://youtu.be/cXnIW0Z0qq8

**Comment by DeputyLOL** [comment]
Wow, looks like you've been busy. Sorry for being quite for recently, there's been a lot going on. 
The display looks awesome, but I couldn't see the first video as you set it to private. :(

"Oh yeah!
 I'm really cool! :-)"
![image](https://cloud.githubusercontent.com/assets/12616126/10419050/1fc431e4-7063-11e5-849d-8d13a97fade3.png)

**Comment by DeputyLOL** [comment]
didn't mean to close it...

**Comment by Alexustas** [comment]
a lot of work was maded
I've make brand new RPM-monitor setup, new font and new font definition

**Comment by DeputyLOL** [comment]
is the display an rpm monitor?

**Comment by Alexustas** [comment]
yes, only two options here: RPM monitor or JSIVariableLabel

**Comment by Alexustas** [comment]
btw, do you know how to convert Airspeed to Mach number ?

**Comment by Alexustas** [comment]
![screenshot323](https://cloud.githubusercontent.com/assets/6713671/10419240/575c85e0-7093-11e5-9f1a-cd07463fdab4.png)

**Comment by DeputyLOL** [comment]
no sorry. didn't you make a mach speed indicator as part of the avionics pack?

**Comment by DeputyLOL** [comment]
Also, if possible. Make the buttons and displays separate objects. Not all attached to the same panel please.

**Comment by Alexustas** [comment]
it's all are separated props, i just bild some kind of MCP assembly for convenience ))

**Comment by Alexustas** [comment]
do you need a dual-mode Speed display (EAS<--> Mach)? or only EAS?

**Comment by DeputyLOL** [comment]
no thanks. I do need a dual mode for the vertical speed and glide slope. If possible have them on the same display

**Comment by Alexustas** [comment]
"and glide slope" - how is it?

**Comment by DeputyLOL** [comment]
its kind of weird. 
In certain planes, the display can  show both vertical speed and 'flight path angle' (vertical angle between prograde and ground). As KSP doesn't real have a use for FPA, I figured you could put something more useful there.
Glide slope is angle that the plane comes into land at.
![image](https://cloud.githubusercontent.com/assets/12616126/10419395/81d95ffc-706e-11e5-89a9-6421ed090b3e.png)
2 mods already use this. NAV Utilities, which RPM is looking into and mechjeb space plane guidance autoland feature.

The type of plane you are modelling after doesn't have that..... I think. But I wanted to include the glide slope in a cockpit display somehow as it very useful to have

**Comment by Alexustas** [comment]
i.e. you need a dual-mode display and dual-mode dial for v/speed, and button for switching this modes?

**Comment by Alexustas** [comment]
G/S input format is "00.0" with step "0.1"?

**Comment by Alexustas** [comment]
So, that's what we have for now
https://youtu.be/AECVEWLaimg

**Comment by DeputyLOL** [comment]
Basically, yes.
A normal G/S is 3 degrees. The NavUtilities mod has 3, 5, 7.5, 10, 15, 20(?) and 25.
I haven't had a chance to measure the max and mins of the mechjeb space plane guidance though.

**Comment by Alexustas** [comment]
so with no decimals?

**Comment by Alexustas** [comment]
oh, i've missed  "7.5" ((

**Comment by DeputyLOL** [comment]
That's just the options for navutility.
mechjeb can take any number.

**Comment by Alexustas** [comment]
what type of switches you want to use to switch between display modes (V/S <--> G/S)?

**Comment by DeputyLOL** [comment]
hmmm.... maybe the simple tumbler switch?

**Comment by Alexustas** [comment]
and this is the right choice! ))

**Comment by Alexustas** [comment]
Do you need "A" warning (overspeed) on the SPEED display?

**Comment by DeputyLOL** [comment]
no. planes have aural alarm for overspeed and a warning appears on the PFD. I already got that.

**Comment by Alexustas** [comment]
OK. In this case, I can do the degree symbol for additional indication what the "Glide slope" mode is selected.
![bandicam 2015-10-13 02-41-10-227](https://cloud.githubusercontent.com/assets/6713671/10438243/56a4f706-7154-11e5-89b6-47bc61178e73.jpg)

**Comment by DeputyLOL** [comment]
yeah, good idea.
Have the 'degree' look like it is part of the other numbers. (remove line inbetween 0 and degree and add the faint grey lines underneath the degree.

**Comment by Alexustas** [comment]
```
  "Have the 'degree' look like it is part of the other numbers. (remove line inbetween 0 and degree"
```

I'm afraid I do not understand what you mean

**Comment by DeputyLOL** [comment]
Sorry.
You see the faint 8s to the left that signify that the number is not currently illuminated. Have that effect on the degree symbol. (bright circle on top, dim circle on bottom)

As for the line, I was referring to the thin white line inbetween the 0 and degree

**Comment by Alexustas** [comment]
ah, it's ok. it's just quick sketch. not a final look ))
 i forgot to put dark-grey "8" behind "degree", sorry

**Comment by Alexustas** [comment]
that's better? ))
![bandicam 2015-10-13 03-13-48-765](https://cloud.githubusercontent.com/assets/6713671/10438955/9c0f16ce-7158-11e5-8f70-27686a278f7b.jpg)

**Comment by DeputyLOL** [comment]
yup!

**Comment by Alexustas** [comment]
Do you need two seperate COURSE display and dials or only one?

**Comment by DeputyLOL** [comment]
in real planes there are 2 and they are separate. I personally don't need a second one.
The course selector is a little useless in KSP, as it is basically heading that takes into account any crosswinds.... KSP doesn't have wind.
Others might want a second one though.

**Comment by Alexustas** [comment]
ok

**Comment by Alexustas** [comment]
Bo-oo-m! I got it! ))

https://youtu.be/fqR4XEDaZew

**Comment by Alexustas** [comment]
https://youtu.be/Ki6joEVREQo

**Comment by DeputyLOL** [comment]
that looks perfect. sorry I have been a bit quiet recently, work was starting to mount up.

**Comment by Alexustas** [comment]
i need clean up something and  then I will upload all MCP stuff

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
MCP Displays:
https://www.dropbox.com/s/0i8rvis4e5z9y4a/EFIS_MCP_Display.zip?dl=0

edti URLs, or put "EFIS_MCP_Display" into "\GameData\ASET\ASET_Props\Instruments\"

**Comment by Alexustas** [comment]
Dials:
https://www.dropbox.com/s/guawdqgh64296pc/MCP_Dials.zip?dl=0

**Comment by Alexustas** [comment]
Rotary wheel for V/S - G/S adjust:
https://www.dropbox.com/s/hkgzptv2yx51x6o/MCP_RotaryWheel.zip?dl=0

**Comment by DeputyLOL** [comment]
SO MANY NEW THINGS FOR TESTING :smiley:
(btw you misspelt glide slope in the page text file for the V/S G/S screen, you spelt it glidesplope)
I corrected it in my setup

**Comment by Alexustas** [comment]
oh, thanks. 
typo - it's my constant problem ((

**Comment by Alexustas** [comment]
btw, i can make inscriptions (or labels, or signs, or... how  it's called in English?) for MCP.
It's will be seperate polygonal texts props. 
ALTITUDE, COURSE, HEADING etc. in same style like "BANK"  on the "heading" dial and "DN <----> UP"

**Comment by Alexustas** [comment]
![bandicam 2015-10-13 23-28-35-028](https://cloud.githubusercontent.com/assets/6713671/10462766/41e33720-7202-11e5-818b-5818a3e360fe.jpg)

**Comment by DeputyLOL** [comment]
yes please. my cockpit display is a different shape to yours so is it possible to have the lines and lables as separate props.

**Comment by DeputyLOL** [comment]
Thinking about it, maybe better to just have a configurable lable prop

**Comment by Alexustas** [comment]
hmmm. i can make prop like "SmallLabelPlate" but with small clearance between text and plate
![bandicam 2015-10-14 00-07-07-621](https://cloud.githubusercontent.com/assets/6713671/10463697/d428b876-7207-11e5-961c-333994602041.jpg)

**Comment by DeputyLOL** [comment]
yes please.

**Comment by Alexustas** [comment]
I hope you understand my idea. I find it hard to describe in words

**Comment by DeputyLOL** [comment]
yeah I understand it. Its going to be fiddly in unity, but I think it could work well.

**Comment by Alexustas** [comment]
yes, you can't see the text itself in Unity, this is not very convenient. What's why i've maked lables with plates underneath.

But you will be able to see text origin and scale, and you get a configurable label without any background. I do not have any other ideas how to do this

**Comment by Alexustas** [comment]
I need to think about how to make this process as easy as possible

**Comment by Alexustas** [comment]
it seems I came up with how to do this

**Comment by DeputyLOL** [comment]
I sense a diagram....

**Comment by Alexustas** [comment]
No, the diagram is not much help here.
ksp reders internals and props only if they placed in a specific Unity layer. if i take a regular labelPlate prop and place them in the "wrong" layer, you stiil be able to see it (and click it and moved etc) in Unity editor, but it not be rendered in KSP

**Comment by Alexustas** [comment]
but your text of course will be rendered ))

**Comment by DeputyLOL** [comment]
that's good then

**Comment by Alexustas** [comment]
![screenshot326](https://cloud.githubusercontent.com/assets/6713671/10465316/162e1f24-7210-11e5-9f07-da482b32cf0b.png)

**Comment by Alexustas** [comment]
Yes! it's work.
you can just replace mu-model and you will get all your label w/o background.
but of course, you need to change a color of text

**Comment by DeputyLOL** [comment]
is it possible to have the labels 'light up'?
currently, all the labels of all your props can be 'on' (white) or 'off' (dark grey).
can the labels be white when off and a brighter glowing white when on?

**Comment by Alexustas** [comment]
no. the stock module used for labels. it's hardcoded by squad and it's not glowing if only black. And i hate it for this.
 what's why i've maked BLACK text oon white plate.

**Comment by DeputyLOL** [comment]
hmmmm.... would the text be colour configurable?

**Comment by Alexustas** [comment]
MOARdv mentioned about the problem: "Short answer, no. It's using a KSP object that doesn't provide any font control (font, justification, etc). That may change when KSP 1.1 drops and we have to deal with the side-effects of Unity 5."
here: https://github.com/Mihara/RasterPropMonitor/issues/401#issuecomment-147192318

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
```
 "hmmmm.... would the text be colour configurable?"
```

everything will work exactly the same as in the SmallLabelPlate but the plate itself will be invisible (in game)

**Comment by DeputyLOL** [comment]
that's ok then

**Comment by Alexustas** [comment]
I've added transforms for text to the all MCP displays

![screenshot327](https://cloud.githubusercontent.com/assets/6713671/10477893/9ad061a4-727b-11e5-8878-8f7dca1f3f3c.png)

![bandicam 2015-10-14 13-00-14-432](https://cloud.githubusercontent.com/assets/6713671/10477898/a5f1693e-727b-11e5-8a35-3d2e69281aaa.jpg)

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/0i8rvis4e5z9y4a/EFIS_MCP_Display.zip?dl=0

**Comment by DeputyLOL** [comment]
I'm having an issue with the vertspeed and glideslope display. It is meant to switch between showing 2 separate variables. 

The vertical speed mode works fine, the glide slope mode doesn't. It appears as a white and black box.
Any ideas?

**Comment by DeputyLOL** [comment]
nevermind fixed it. I was still using the type version and forgot to change the textfile name in the monitor config.
