### ISSUE TITLE
Bank Adjuster dial

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#12]
![image](https://cloud.githubusercontent.com/assets/12616126/10375233/3f4d3c20-6def-11e5-8399-f92b012a6a25.png)

A 7 point switch for adjusting bank. Always starts at top and can move left or right.

**Comment by Alexustas** [comment]
do you have some fotos of this thing?

**Comment by DeputyLOL** [comment]
In real aircraft. It is part of the heading knob. And it is used to limit the amount the autopilot is allowed to bank the aircraft when following a heading.

To keep It simple, I suggest a separate dial.
To look real, I suggest adding another dial on to the bottom on the select knob you just made.

**Comment by DeputyLOL** [comment]
![image](https://cloud.githubusercontent.com/assets/12616126/10376196/7b074756-6df4-11e5-8912-bdec36bd314a.png)

**Comment by DeputyLOL** [comment]
It is difficult to get a picture of it.
If you want to make it, simply add another knob on to the bottom of the one you just made.

**Comment by Alexustas** [comment]
ohh, i know that dial, just your first picture me a little confused. I thought it was some kind of a separate switcher :-)

**Comment by DeputyLOL** [comment]
Are you going to do a double dial knob for heading and bank?
WITH A SELECT BUTTON??????

**Comment by Alexustas** [comment]
but I think it will be very difficult to click precisely this switch in the KSP

**Comment by DeputyLOL** [comment]
yeah, that's what I thought. That's why I considered using a separate switch.

**Comment by Alexustas** [comment]
in the FSX i'm using mouse will for rotate dials and it also not easy some times

**Comment by Alexustas** [comment]
yes. in our case will be better to use separate switch. double dial may couse problem in KSP

**Comment by DeputyLOL** [comment]
:(

**Comment by Alexustas** [comment]
although I had an idea how to solve this problem

**Comment by DeputyLOL** [comment]
whats that?

**Comment by Alexustas** [comment]
Wait a minute. I find it easier to draw than to explain it in English ))

**Comment by DeputyLOL** [comment]
fair enough

**Comment by Alexustas** [comment]
I can try to do colliders in the form of trapezoids

![bandicam 2015-10-09 01-06-00-114](https://cloud.githubusercontent.com/assets/6713671/10376909/3942e52c-6e22-11e5-8a17-a3d183b8822e.jpg)

**Comment by DeputyLOL** [comment]
looks good, I think that the dial itself should be very short so you can easily click on the far side collider

**Comment by Alexustas** [comment]
click on top or bottom side of switcher changes heading, on left or right bankig

**Comment by Alexustas** [comment]
ok. but for now i'm doing a 2nd version of dial with out button. issue #7

**Comment by Alexustas** [comment]
actual "bank limit" is from 10 to 30 deg (or 5...25) and has no differences for the right and left sides (positive / negative). but on your first picture scale is 30...0...30.  and I'm a little confused
![mcp747_7](https://cloud.githubusercontent.com/assets/6713671/10406718/20d39328-6f04-11e5-8b60-2abd8110b3ec.jpg)
![heading altitude-75](https://cloud.githubusercontent.com/assets/6713671/10406725/375a3d2c-6f04-11e5-9895-93d68f0ebffc.jpg)

**Comment by Alexustas** [comment]
btw, dial model is almost finished
![bandicam 2015-10-10 04-18-36-357](https://cloud.githubusercontent.com/assets/6713671/10406941/5bb85c6a-6f06-11e5-908e-3ecb9d197f61.jpg)
![bandicam 2015-10-10 04-18-48-978](https://cloud.githubusercontent.com/assets/6713671/10406942/5de0ecaa-6f06-11e5-9611-4b210f51c2b2.jpg)
![bandicam 2015-10-10 04-18-54-156](https://cloud.githubusercontent.com/assets/6713671/10406945/61d557e2-6f06-11e5-825c-4abd629e09df.jpg)

colliders:

![bandicam 2015-10-10 04-19-15-668](https://cloud.githubusercontent.com/assets/6713671/10406949/63bbc956-6f06-11e5-85f3-d0d65a287d74.jpg)

**Comment by DeputyLOL** [comment]
In real life the dial limits the amount the aircraft can bank. (but this isn't possible to KSP).

I made up the dial in the first picture, its purpose is to work with the pilot assist mod which has the ability to roll the aircraft to a certain degree and hold it there. (hopefully RPM will implement it).

**Comment by Alexustas** [comment]
OK. Now I understand everything

**Comment by DeputyLOL** [comment]
:)

**Comment by Alexustas** [comment]
![bandicam 2015-10-10 16-38-01-786](https://cloud.githubusercontent.com/assets/6713671/10410766/5a06ccbe-6f6d-11e5-8044-acc9d683ccdc.jpg)

**Comment by DeputyLOL** [comment]
3 please

**Comment by Alexustas** [comment]
ok. i like №4 too

**Comment by Alexustas** [comment]
whether on the scale also place a signature "BANK" or "ROLL"?

**Comment by DeputyLOL** [comment]
yeah, I change my mind to 4 again.

**Comment by DeputyLOL** [comment]
BANK

**Comment by Alexustas** [comment]
So this part of the panel will look something like this. Yes?

![bandicam 2015-10-10 17-08-03-737](https://cloud.githubusercontent.com/assets/6713671/10410866/ac87f964-6f71-11e5-8e58-15f59f7c6d8f.jpg)

**Comment by DeputyLOL** [comment]
yeah, but without the red 4

**Comment by Alexustas** [comment]
Of course :)
![bandicam 2015-10-10 17-10-48-337](https://cloud.githubusercontent.com/assets/6713671/10410872/eb1197bc-6f71-11e5-96d6-14ccffc1df3d.jpg)

**Comment by DeputyLOL** [comment]
the colliders would have to change though. as the bank dial is invested on the right side.

**Comment by Alexustas** [comment]
i'm afraid I do not quite understand. please explain more

**Comment by Alexustas** [comment]
I think it would be easier to understand each other, if you show me the approximate layout of all instruments and switches in your cabin

**Comment by DeputyLOL** [comment]
If you look on the left side, the top of the bank dial is positive and the bottom is negative.
On the right, the top is negative and the bottom is positive.
It might be better to have 2 sets of colliders on both sides, but then you also have the heading bar to deal with....

**Comment by DeputyLOL** [comment]
Also, my cockpit is very messy as its constantly changing when new features become available. Its also got a lot of random button and lights that I'm testing. The Auto pilot is very disorganised at the moment

**Comment by DeputyLOL** [comment]
let me try with this.
![heading diagram](https://cloud.githubusercontent.com/assets/12616126/10410969/dc0458de-6f4b-11e5-9342-57d209b1532c.png)

**Comment by Alexustas** [comment]
Oh yeah! I reworked the "Alcor" cockpit  so many times... ((

**Comment by Alexustas** [comment]
![bandicam 2015-10-10 17-46-42-278](https://cloud.githubusercontent.com/assets/6713671/10410985/f83490b6-6f76-11e5-8265-564004150384.jpg)

**Comment by DeputyLOL** [comment]
yup! that's it.

**Comment by Alexustas** [comment]
ок

**Comment by Alexustas** [comment]
![bandicam 2015-10-10 18-05-00-455](https://cloud.githubusercontent.com/assets/6713671/10411025/81c44d24-6f79-11e5-96c5-3c41d2123a44.jpg)
![bandicam 2015-10-10 18-04-49-580](https://cloud.githubusercontent.com/assets/6713671/10411026/83ee1ab2-6f79-11e5-81ed-2e50c1b34531.jpg)

**Comment by DeputyLOL** [comment]
is the heading colliders on the actual heading knob part?

**Comment by Alexustas** [comment]
this is ONE assembly (prop), including signature ))

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
https://youtu.be/yHfG_L45qPk

**Comment by DeputyLOL** [comment]
looks awesome!
how did you get the heading dial to change the heading so quickly?

**Comment by Alexustas** [comment]
I'm using 'incrementCurve {}'

**Comment by Alexustas** [comment]
more tests
https://youtu.be/M3aV1ImQwxo

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/nfjl8sxfz8ryzqh/HeadingBankDial.zip?dl=0

**Comment by DeputyLOL** [comment]
me too.. but mine just moves slowly and gradually starts to increase more.
Yours was increasing very quickly...

**Comment by DeputyLOL** [comment]
thanks
