### ISSUE TITLE
New rotary switch model

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#13]
Could you make a different model for all of you rotary switches please? (2point, 3point 4point)
![image](https://cloud.githubusercontent.com/assets/12616126/10375313/b3df8c64-6def-11e5-9c2e-b68486a1d541.png)

**Comment by Alexustas** [comment]
![bandicam 2015-10-12 23-57-16-223](https://cloud.githubusercontent.com/assets/6713671/10434749/3b11c6b6-713d-11e5-9f67-98a4e8ef4e28.jpg)
![bandicam 2015-10-12 23-57-38-580](https://cloud.githubusercontent.com/assets/6713671/10434752/3dd06d30-713d-11e5-8cab-3391e2e3e07e.jpg)
![bandicam 2015-10-12 23-57-45-934](https://cloud.githubusercontent.com/assets/6713671/10434753/3ffe8394-713d-11e5-9a8d-aad50b9d7e6b.jpg)

**Comment by Alexustas** [comment]
![bandicam 2015-10-13 00-39-40-296](https://cloud.githubusercontent.com/assets/6713671/10435637/0b1a23ee-7143-11e5-801f-0105426ab495.jpg)

**Comment by DeputyLOL** [comment]
looking good!

**Comment by Alexustas** [comment]
https://youtu.be/K5pixhM050s

**Comment by Alexustas** [comment]
https://youtu.be/oDaeSG84o6I

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/i3ececlvjafhtcs/ASET_B-Knob.zip?dl=0

put "BKnob.wav" into the "GameData\ASET\ASET_Avionics\ModernPack\Sounds"

**Comment by DeputyLOL** [comment]
thanks

**Comment by Alexustas** [comment]
if all ok, you can close this issue

**Comment by DeputyLOL** [comment]
The colliders are top and bottom. For the 360 rotating selector dials, that's ok.
For these switches, I think it would be better if the colliders were left and right.

**Comment by Alexustas** [comment]
ok

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/7jv0hxjlbrts29b/ASET_B-Knob_3pos.zip?dl=0
replace existing MU-files
