### ISSUE TITLE
NASA LM X-Pointer instrument

### ISSUE THREAD

**Issue by Alexustas** [Alexustas/Props-requests#15]
![bandicam 2015-10-17 16-32-41-210](https://cloud.githubusercontent.com/assets/6713671/10558325/59ae4460-74ed-11e5-87f8-1c350b8630b2.jpg)

**Comment by MOARdV** [comment]
Cool!  With these Apollo parts showing up, maybe I need to find a primitive LEM to use for a lander, since the ALCOR lander is a little too advanced for analog instruments :)

**Comment by Alexustas** [comment]
By the way, I started to thinking about some Historical props pack ))

**Comment by Alexustas** [comment]
depending on the selected mode lights up appropriate inscription

![bandicam 2015-10-17 20-59-10-907](https://cloud.githubusercontent.com/assets/6713671/10559406/2863ca36-7512-11e5-8c52-a6e509b20827.jpg)

**Comment by Alexustas** [comment]
![bandicam 2015-10-17 21-01-38-973](https://cloud.githubusercontent.com/assets/6713671/10559427/6b4e425e-7512-11e5-95fd-8c4b9d799deb.jpg)

**Comment by MOARdV** [comment]
Oh, that's a nice touch.  I like the mode indicators.

**Comment by Alexustas** [comment]
also, I've add scale indication. 

a similar indication present on the original device as well

![lm_crosspointer](https://cloud.githubusercontent.com/assets/6713671/10560544/11467efc-7530-11e5-9bf4-ccddad8eb1f5.jpg)

**Comment by Alexustas** [comment]
X-Pointer test

https://youtu.be/TGPKFbvy_98

my first successful "blind" approach and docking using FDAI and X-pointer

https://youtu.be/teKZAhMLpI8

**Comment by MOARdV** [comment]
That is coming together very well.
