### ISSUE TITLE
Stand-alone Rotation Control joystick

### ISSUE THREAD

**Issue by MOARdV** [Alexustas/Props-requests#19]
Would it be possible to take the ALCOR rotation control joystick and remove the support arm from it, so that it is only the housing and joystick?  This would make it much easier to use in cockpits that do not have a good place in front of the controller to "attach" the support arm.

**Comment by Alexustas** [comment]
something like this?

![2015-11-03 02-14-23-445](https://cloud.githubusercontent.com/assets/6713671/10892999/adf1db64-81d0-11e5-9a1d-96c18e29c617.jpg)

**Comment by MOARdV** [comment]
Yes, something like that.

**Comment by Alexustas** [comment]
Ok
DL: https://www.dropbox.com/s/1y77f184oco0ejd/RotationCtrl_V2.zip?dl=0

**Comment by Alexustas** [comment]
So, can I close this issue?

**Comment by MOARdV** [comment]
Yes.  Thank you.
