### ISSUE TITLE
Alarm light/Button

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#22]
Shouldn't be too hard, I'm basically looking for a square light that can act as a button. The button would look the same when it is on or off (meaning it doesn't 'stay down' when its active). I want to make this:
![image](https://cloud.githubusercontent.com/assets/12616126/11125706/4765d086-8963-11e5-9140-b7254953f86c.png)
When theres a problem.... they light up.

Don't worry about the flat panel with the other lights, just the fire bell and master caution.

Let me know what you think please.

**Comment by DeputyLOL** [comment]
I was also wondering if this could have the glow of the interior lights so that they are more noticeable? 
The radius would be very very small.

**Comment by Alexustas** [comment]
it must be two separate buttons or one prop?

**Comment by DeputyLOL** [comment]
separate. because there's 2 more on the co pilots side, the other way round.

**Comment by DeputyLOL** [comment]
I think i need a panel now along with the red and yellow lights.
There would have to be two separate props for both sides. Only 4 lights each.
Left:
FLT CONT |  ELEC
FUEL   |   OVHT/DET
Right:
HYD    |   ENG
IRS  |  OVERHEAD

**Comment by DeputyLOL** [comment]
Never mind, I used the retro buttons with a custom texture to achieve this.
