### ISSUE TITLE
Note Prop

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#24]
I haven't heard from you in a while, hope all is ok.

I was hoping to get a simple sticky note prop with INOP written on it.
I want to have something to label incomplete/broken instruments and controls in my cockpit. I'm showing my cockpit to my family and want something to cover things not working.

**Comment by DeputyLOL** [comment]
nevermind, not needed anymore.

**Comment by Alexustas** [comment]
Sorry, I was very busy last month ((

**Comment by DeputyLOL** [comment]
that's ok, glad your back.
