### ISSUE TITLE
Small button prop

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#25]
Hi again, I know your probably still busy because I haven't heard from you. :(
If you are still working on this then I have a small request. 
If not then thank you for all the props you provided me with. :D 

A round black button similar to the one used in the throttle pedestal for the horn cutout.

Thanks.

**Comment by Alexustas** [comment]
>  for the horn cutout.

like this?

![2016-07-29 13-48-46-096](https://cloud.githubusercontent.com/assets/6713671/17241397/37a8347a-5593-11e6-8dcc-078ece452d0c.jpg)

**Comment by DeputyLOL** [comment]
yeah basically. thank you

**Comment by Alexustas** [comment]
after pressing this button should be locked in the down position or it should go back up?

**Comment by DeputyLOL** [comment]
Go back up please.

**Comment by Alexustas** [comment]
ok

**Comment by Alexustas** [comment]
![2016-07-30 01-30-42-486](https://cloud.githubusercontent.com/assets/6713671/17260994/622940ec-55f5-11e6-907d-d1f882ae6c5a.jpg)

**Comment by DeputyLOL** [comment]
lovely!

**Comment by Alexustas** [comment]
OK.
I do not plan to include this prop in the package, so you can add it to your mod
https://www.dropbox.com/s/kjelo7ottq7d7bn/DL_SmallButton.zip?dl=0

**Comment by DeputyLOL** [comment]
thank you.

**Comment by DeputyLOL** [comment]
This is probably closable now, ill let you know if there are any issues. Thanks again!
