### ISSUE TITLE
Simple Tumbler Switcher and Switcher Cover

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#3]
Another request please:
Two variants of the switch with cover. 
 One with no label or light so it is much shorter.
 And one with no cover, label or light.

Do you think that is possible?

**Comment by Alexustas** [comment]
I can make a separate prop "Switcher cover" with collider and opening animation, so may to place it over the switcher that you need to "protect". And then you need to open cover first, before you will be able to switch protected tumber switch

![switch-guard-red-cover-image-x-web](https://cloud.githubusercontent.com/assets/6713671/10263020/9d5b94e4-6a00-11e5-9979-e3ddcd9ee660.jpg)

**Comment by DeputyLOL** [comment]
Yes please. But the tumbler switch would be the thin silver type. 

![image](https://cloud.githubusercontent.com/assets/12616126/10263110/3ebe21da-69d9-11e5-900f-a4c9797ed487.png)

**Comment by Alexustas** [comment]
![bandicam 2015-10-03 19-45-34-623](https://cloud.githubusercontent.com/assets/6713671/10263217/a69391fe-6a07-11e5-9215-74dc2690a7b4.jpg)
![bandicam 2015-10-03 19-46-30-878](https://cloud.githubusercontent.com/assets/6713671/10263218/aa91d784-6a07-11e5-98dd-32720612b046.jpg)

and now adding a cover prop

![bandicam 2015-10-03 19-45-54-091](https://cloud.githubusercontent.com/assets/6713671/10263219/b0a08be8-6a07-11e5-838a-9746549c64b7.jpg)
![bandicam 2015-10-03 19-46-08-244](https://cloud.githubusercontent.com/assets/6713671/10263220/b3b66c8a-6a07-11e5-8f7a-76635ed3d86e.jpg)
![bandicam 2015-10-03 19-46-25-111](https://cloud.githubusercontent.com/assets/6713671/10263221/b6225dee-6a07-11e5-944d-170f0c72b332.jpg)

**Comment by DeputyLOL** [comment]
YES! Thank you!!!

**Comment by Alexustas** [comment]
ok. I need to do texture stuff first, then animations and basic config

**Comment by Alexustas** [comment]
and yes. I can make black and red cover if you need

**Comment by DeputyLOL** [comment]
thank you. I think both colours would be helpful

**Comment by Alexustas** [comment]
it will be one prop with textureShift module, so you can chage colour as you need

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
ta-da-aa-m!
https://youtu.be/iB6t3YL3gPg

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/esifwgmgydhvw59/new_switchers.zip?dl=0

Put 2 sound files in the /ASET_Props/Sounds/

**Comment by DeputyLOL** [comment]
OMGOMGOMGOMGOMGOMGOMGOM *explodes

**Comment by DeputyLOL** [comment]
Thanks!

**Comment by DeputyLOL** [comment]
Should I put all requests for buttons and switches here?

**Comment by Alexustas** [comment]
no. it's will be better for me if 'one prop - one request'

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
btw, switcher prop and cover prop have same scale and pivot

**Comment by DeputyLOL** [comment]
I'm testing them right now.
I think I'm going to make it so that the switch is always off when the cover is down.

**Comment by DeputyLOL** [comment]
you said that you were going to include a texture transform so I could have black or red. Is that there or should I copy it and change one to have a black texture?

**Comment by DeputyLOL** [comment]
Switch with cover is the old switch with cover model.
Simple switch is good.

**Comment by Alexustas** [comment]
```
 MODULE
 {
      name = JSIPropTextureShift

      transformToShift = CoverObj
      layerToShift = _MainTex _Emissive
      x = 0.0
      y = 0.50 <<<<
 }
```

'y = 0.0' - for RED cover, and 'y = 0.50' for BLACK colour

**Comment by Alexustas** [comment]
ooh! sorry!
https://www.dropbox.com/s/esifwgmgydhvw59/new_switchers.zip?dl=0

**Comment by DeputyLOL** [comment]
All better now. thank you!

**Comment by DeputyLOL** [comment]
looks awesome. I've used it on my GPWS switches.
I've put together a video of it. Not the best quality sorry.
https://youtu.be/nKgdGkVJY24
