### ISSUE TITLE
Circuit Braker Switch

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#5]
A pull switch that looks like it isn't meant for regular use.
![image](https://cloud.githubusercontent.com/assets/12616126/10269569/c0813dd8-6ad3-11e5-8b62-10ad783ab64a.png)
When its out, its off.
When its in, its on.

**Comment by DeputyLOL** [comment]
Could have a small lable or texture on the front

**Comment by Alexustas** [comment]
i need more info about "small label or texture" ?

**Comment by DeputyLOL** [comment]
Circuit brakers have a small number on the front of them and a label either above or below to indicate what they do.
![image](https://cloud.githubusercontent.com/assets/12616126/10317318/b0367266-6c5b-11e5-8d8e-06101e0d654a.png)

Ideally, the front of the circuit braker could have different textures.
The labels can be done with a separate circuit braker panel prop.

**Comment by DeputyLOL** [comment]
Circuit braker should also be colourable

**Comment by DeputyLOL** [comment]
Very much like the ones you have in the ALCOR mod, but can act as a switch.

**Comment by Alexustas** [comment]
:-)  I mean what kind of texture YOU want. One letter or number? 3-5 symbols? icons?  etc.

**Comment by Alexustas** [comment]
How many different lables you need?

**Comment by DeputyLOL** [comment]
It will probably just be numbers (fuse ratings). Like the ones currently on ALCOR mod.
I'm not entirely sure yet, that's why I wanted textures, so I could add or change them if needed.

**Comment by Alexustas** [comment]
16 different textures will be enough?

**Comment by DeputyLOL** [comment]
yup

**Comment by DeputyLOL** [comment]
they should default to 1 btw.
Which would be the 'in' position.

**Comment by Alexustas** [comment]
![bandicam 2015-10-07 00-13-27-360](https://cloud.githubusercontent.com/assets/6713671/10317876/59ef9fb8-6c88-11e5-9bc9-3636790e33cc.jpg)

green circle on the top - transform with switchable texture

**Comment by DeputyLOL** [comment]
Looks awesome

**Comment by Alexustas** [comment]
![bandicam 2015-10-07 00-18-18-040](https://cloud.githubusercontent.com/assets/6713671/10317991/fc596464-6c88-11e5-94e1-d50f8b8bb28d.jpg)
do you need to change a colour of this green mesh?

**Comment by DeputyLOL** [comment]
Yes please. The base and cylinder part can just be grey and a slightly lighter grey

**Comment by Alexustas** [comment]
ok

**Comment by Alexustas** [comment]
"ON"

![bandicam 2015-10-07 00-29-53-988](https://cloud.githubusercontent.com/assets/6713671/10318310/a08f3dbe-6c8a-11e5-9bef-77326ea57d61.jpg)

OFF

![bandicam 2015-10-07 00-29-41-942](https://cloud.githubusercontent.com/assets/6713671/10318314/a487a99c-6c8a-11e5-9442-513beb27aed7.jpg)

**Comment by DeputyLOL** [comment]
exactly

**Comment by Alexustas** [comment]
ok. I need about a 1 hour

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
progress report

![bandicam 2015-10-07 01-25-23-764](https://cloud.githubusercontent.com/assets/6713671/10319895/5c0b4478-6c92-11e5-941f-2c1bd9680255.jpg)

**Comment by Alexustas** [comment]
preview:

https://youtu.be/LaHrYbUw4I0

**Comment by Alexustas** [comment]
![circuitbreakerv2diffuse](https://cloud.githubusercontent.com/assets/6713671/10320642/57d2d912-6c96-11e5-91df-68d91eb120e5.png)

you get 20 'cells' for different labels

**Comment by DeputyLOL** [comment]
Brilliant!

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/vly5atisk8h59ps/CircuitBreakerV2.zip?dl=0

**Comment by DeputyLOL** [comment]
thank you. testing now

**Comment by Alexustas** [comment]
let me know if all ok

**Comment by DeputyLOL** [comment]
not sure if the texture shift is working as intended. When I try and select a black colour, unity shows me that the rest of the switch turns red.
I think its because the texture for the red top is moving where the switch textures used to be.
![image](https://cloud.githubusercontent.com/assets/12616126/10321807/979cb5a0-6c72-11e5-8f4a-27c9ab30d050.png)

**Comment by DeputyLOL** [comment]
i think there needs to be a separate texture for the switch texture

**Comment by Alexustas** [comment]
for customizing labels you need to use 'JSIPropTextureShift' module in config. 
In Unity all that props look exactly same but in game all be fine.

**Comment by Alexustas** [comment]
![circuitbreakerv2diffuse](https://cloud.githubusercontent.com/assets/6713671/10322345/2126544e-6c9f-11e5-9fe0-de50e116bb2a.png)

for example, if i need a label "20" on black bg, a config will looks like:

```
  MODULE
  {
        name = JSIPropTextureShift
        transformToShift = CB_TopObj
        x = 0.40
        y = 0.80
        layerToShift = _MainTex 
  }
```

each square 0.2 x 0.2, zero in the left bottom corner.

if i need a label "10" on red bg, a config will looks like:

```
  MODULE
  {
        name = JSIPropTextureShift
        transformToShift = CB_TopObj
        x = 0.20
        y = 0.40
        layerToShift = _MainTex 
  }
```

**Comment by Alexustas** [comment]
Unity moves (offset) texture on the ALL meshes, 'JSIPropTextureShift' module move texture only on specified mesh (transformToShift)

https://github.com/Mihara/RasterPropMonitor/wiki/Prop-modules#jsiproptextureshift

**Comment by DeputyLOL** [comment]
Never mind. I finally got a chance to test it in KSP and it looks ok. 
Works perfectly. Thank you.

**Comment by Alexustas** [comment]
i'm glad to help. and now time for the next requested prop
