### ISSUE TITLE
Mod sorting and reference props.

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#51]
I've just got back to modding and im trying to sort out my mod so that it uses as little space as possible. 

I rely on a lot of your props when building my cockpit. I change the config of every prop but often leave the model and texture untouched, meaning that I have a lot of models and textures that are exactly the same as the ones in the ASET folder.

Basically:
I don't want to have duplicate models and textures from your ASET props. I'd like to be able to use this in the .cfg in my mod folder.
  
    MODEL
	{
		model = ASET/ASET_Props/Misc/CrewManual01/CrewManual01
		texture = CrewManualDiffuse,ASET/ASET_Props/Misc/CrewManual01/CrewManualDiffuse
                texture = ManualRingsAndMarks,ASET/ASET_Props/Misc/CrewManual01/ManualRingsAndMarks
	}

Problem is it doesn't always work and i'm not sure what i'm doing wrong. If you have any advice I'd be very grateful.

**Comment by MOARdV** [comment]
FWIW, I do exactly that all the time (take a loot at MOARdV/MAS_ASET in the MAS directory - there are nothing but config files).

Do you have any specific props where that's not working?  The only ones I saw where that happened consistently were the old push buttons (AutoPilotSwitch and AutoPilotSwitch2 in ASET/ASET_Props/Control), but I haven't used those props recently.

**Comment by DeputyLOL** [comment]
The crew manual prop. (example in first post) It throws an exception and stops any prop after it from loading.
I think its because its got more than one texture but im not sure.

A little rusty at the moment.

**Comment by MOARdV** [comment]
For the crew manual, I did not replace the textures in the MODEL node.  All I had was the `model =` line, and it loads (in MAS).

**Comment by DeputyLOL** [comment]
Im using RPM but ill try it.
Thanks

**Comment by DeputyLOL** [comment]
yeah, that works. Ill open this issue again if i run into more problems.

Thanks for the help.
