### ISSUE TITLE
New warning light model.

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#6]
I love the current model you have for the indicators, but do you think you could make one without the boarder. The boarder covers up some of my texture.

Its basically a rectangle with a texture on the front. If possible can you keep the Icon texture format the same so I can copy all the existing textures over to the new one.

**Comment by Alexustas** [comment]
do you have your one textures or you are using ALCOR texture?

**Comment by DeputyLOL** [comment]
I have my own, but I used the alcor textures as a sort of template.
![model001](https://cloud.githubusercontent.com/assets/12616126/10332730/226e46a8-6cd7-11e5-83ee-96a8641f0488.png)

**Comment by Alexustas** [comment]
ok.. thats what i need

**Comment by DeputyLOL** [comment]
i have more than one.
![model001](https://cloud.githubusercontent.com/assets/12616126/10332789/95f974d0-6cd7-11e5-8612-686099e62f0a.png)

**Comment by Alexustas** [comment]
![bandicam 2015-10-07 15-03-55-609](https://cloud.githubusercontent.com/assets/6713671/10333301/b007953c-6d04-11e5-9462-f938b6bb4e38.jpg)

**Comment by Alexustas** [comment]
it have same dimensions as TabloIndicator. 

![bandicam 2015-10-07 15-10-43-464](https://cloud.githubusercontent.com/assets/6713671/10333422/a20fca48-6d05-11e5-8614-f9c8144008e2.jpg)

**Comment by Alexustas** [comment]
do you need a collider mesh on this prop?

**Comment by DeputyLOL** [comment]
Yes please.

**Comment by DeputyLOL** [comment]
Do you think you could make a button/alarm? It would look like this:
![image](https://cloud.githubusercontent.com/assets/12616126/10333599/e9498364-6cdc-11e5-9a8d-85fdde2b3f38.png)
The lights are square and have a transparent section around the edges. (you can ignore the FMC one)
Do you think you could also do the back plate as well.

**Comment by Alexustas** [comment]
texture name is "model001" ?

**Comment by DeputyLOL** [comment]
yes

**Comment by Alexustas** [comment]
I prefer not to deal with transparency unless absolutely necessary. I think we can do it without transparency

**Comment by DeputyLOL** [comment]
I mean that there is a light behind the switch. When the light is on, the letters and sides of the switch are lit up.
All that means is that when the light is on, the edges are lit up as well as the letters on the front.
(i just mentioned it because it wasn't very clear in the picture)

**Comment by DeputyLOL** [comment]
Also I've been meaning to ask. How do I get an indicator to light up an area around it.
Like your internal lights and the abort button. When I put the internal lights in my cockpit, they lit up but didn't light the area around them.
Is there some way to edit the colour, intensity and radius of a light and if it flashes?

**Comment by Alexustas** [comment]
[A/P Alarm] I think I can get the same effect by using common  emissive animation.

**Comment by DeputyLOL** [comment]
cool

**Comment by Alexustas** [comment]
Any lights sources in KSP dramatically kill FPS :- ( If you have a lot of working indicators in the cabin it drop your FPS rate under floor. also KSP use only 8 lights in the scene by default. it causes random blinking of lights like a strobe in the night club :)

that's why i don't add Lights to the indicators

**Comment by DeputyLOL** [comment]
what about the interior lights?

**Comment by Alexustas** [comment]
LightBox prop don't have a lights source because normally all lights sources exist in the inetrnal model. the lamp prop is "just for show".  I can make the same prop but WITH light source, the only propblem is how you can adjust light property from config...

**Comment by DeputyLOL** [comment]
All, i need is for the light to be on when the lamp is on and the light to be off when the lamp is off.
:/

**Comment by Alexustas** [comment]
please, start a new issue for "AP alrm" prop and for "Interior Lights" props

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
do you need an "ready-to-use" emissive animation on warning light (like it was on TabloIndicator) or you prefer to use  "coloredObject" and "passiveColor" - "activeColor" for more control?

**Comment by DeputyLOL** [comment]
I think for now, ill be happy with the animations.
Ideally, there would be one 'square' in the texture file that is an off light (you can see it on the first texture underneath ENGINE FAILURE.
The lamp would then switch between the generic off texture and the lighted texture. 
I tried this with the TabloIndicator but it only showed the dull version and I didn't know how to correct it.

**Comment by DeputyLOL** [comment]
So if possible, could you have the option to have either an animated light or one that uses 'transform' to switch between an off light and an on light.
I want this so that i can edit my lights to make them look like they are shiny and brighter than they appear.

**Comment by Alexustas** [comment]
so, you need a clear black "square" for OFF state?

**Comment by DeputyLOL** [comment]
Basically yes, I have one already in the texture file.

**Comment by Alexustas** [comment]
hmmm, i think i can make it more realistic.

if OFF, texture is visible but just a little

![bandicam 2015-10-07 16-53-56-936](https://cloud.githubusercontent.com/assets/6713671/10335683/4eb3b4c2-6d14-11e5-85ff-544248433b06.jpg)

when ON, it's clear visible and shiny (lit)

![bandicam 2015-10-07 16-54-24-613](https://cloud.githubusercontent.com/assets/6713671/10335714/93a28770-6d14-11e5-80dd-822cb19122aa.jpg)

**Comment by DeputyLOL** [comment]
It looks good but my OCD wants perfect.
If you can make the off square use grey instead of red then it would be perfect. 
In real planes, the light behind the indicator is red, so you only see red when the light is on.
When it is off, you don't see any colour.

**Comment by Alexustas** [comment]
I mean what it is hard but still possible to read text

![bandicam 2015-10-07 17-14-13-309](https://cloud.githubusercontent.com/assets/6713671/10335989/16aec8f2-6d17-11e5-8a95-0dc6cb99e93c.jpg)

![bandicam 2015-10-07 17-14-29-621](https://cloud.githubusercontent.com/assets/6713671/10335992/1d2b7d2e-6d17-11e5-90f2-8be1a0ad1743.jpg)

![bandicam 2015-10-07 17-18-13-159](https://cloud.githubusercontent.com/assets/6713671/10336020/6e1f0066-6d17-11e5-89ec-6269ee74690e.jpg)

**Comment by DeputyLOL** [comment]
yes, still possible to read, but doesn't have any colour when it is switched off.

**Comment by Alexustas** [comment]
I finally understood what you mean. then it's "OFF" it must be grey coloured

**Comment by DeputyLOL** [comment]
yeah that's it. sorry if I made it sound confusing.

**Comment by Alexustas** [comment]
No, it's my awful English :(

**Comment by Alexustas** [comment]
i think. i can make this (grey text if "OFF" and bright coloured if "ON") but it will require a lot of config work from you and editing your textures

**Comment by DeputyLOL** [comment]
I can create an off version of every indicator texture I have if needed.

**Comment by Alexustas** [comment]
yes, but additional texture ... more memory

**Comment by Alexustas** [comment]
but it easiest way to achieve desired result

**Comment by DeputyLOL** [comment]
yeah. i like using textures because I can change it to exactly what i want.
I'll try the text way and see if it looks good.

**Comment by Alexustas** [comment]
how about a 2-colored labels, like "PULL UP", "GROUN PROX" ?  how its must look like when  it OFF?

**Comment by DeputyLOL** [comment]
ignore the ground prox. I'm going to phase out most of the 2 coloured labels. I'll post the updated versions here soon.

**Comment by Alexustas** [comment]
that's what we get by using two versions of the textures: 

![bandicam 2015-10-07 17-58-40-620](https://cloud.githubusercontent.com/assets/6713671/10336794/2cb14246-6d1d-11e5-8d85-f24d065d5d2b.jpg)

![bandicam 2015-10-07 17-59-12-639](https://cloud.githubusercontent.com/assets/6713671/10336826/53969a0a-6d1d-11e5-9cfd-ba330e257687.jpg)

**Comment by DeputyLOL** [comment]
yes, that's perfect

**Comment by Alexustas** [comment]
There is only is one limitation. it would be impossible to make the effect off incandescent lamps. i mean lable light up instantly

**Comment by DeputyLOL** [comment]
If you means they change from lit to unlit instantly then that's fine.
Sorry for going quite, I had to deal with something

**Comment by DeputyLOL** [comment]
![model001](https://cloud.githubusercontent.com/assets/12616126/10337654/26ab1abc-6cf9-11e5-8f6a-786580acf4ab.png)

**Comment by DeputyLOL** [comment]
should he texture file has what the lights would look like when they are lit?
(should they use bright colours?)

**Comment by DeputyLOL** [comment]
Sorry ignore previous texture. This is new one.
![model001](https://cloud.githubusercontent.com/assets/12616126/10337964/3230cc86-6cfb-11e5-94ef-87562208ca2a.png)
and
![model001](https://cloud.githubusercontent.com/assets/12616126/10337970/3b9fb516-6cfb-11e5-9c46-8d999e56062d.png)
(ignore the ones that don't have a black background except the seatbelt and no smoking lights)

**Comment by Alexustas** [comment]
i will be off in a next few hours

**Comment by DeputyLOL** [comment]
ok

**Comment by Alexustas** [comment]
test:
https://youtu.be/UkMZacfQzLk

**Comment by DeputyLOL** [comment]
looks good.

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/m20wigdktu4lbhx/WarningLight.zip?dl=0

**Comment by Alexustas** [comment]
So, you need two textures:
- coloured
- greyscaled (just desaturate and reduce brighness of colored texture)

**Comment by Alexustas** [comment]
Do not change the names of the textures

**Comment by Alexustas** [comment]
and you need to edit an old configs :(
1. find and replace the name of animation. 
   Old:
   
   ```
    animationName = TabloIndicatorAnim
   ```

New:

```
     animationName = WL_ONanim
```

**Comment by DeputyLOL** [comment]
thank you, ill start testing

**Comment by Alexustas** [comment]
2
 add a second 'JSIPropTextureShift' module for "OFF" mesh, just copy-paste the existing module and change 'transformToShift' name to ''TabloPlateOFF".

NOTE. the value of X and Y in both modules must be the SAME

**Comment by Alexustas** [comment]
3

this is Grid tamplate for labels
![wl_grid_template](https://cloud.githubusercontent.com/assets/6713671/10347828/9471e37e-6d57-11e5-9cd1-d287961de041.png)

**Comment by Alexustas** [comment]
and last one.

the box (or case, or body) mesh of indicator uses a very small piece of "grayLabels" texture

![bandicam 2015-10-08 01-03-24-842](https://cloud.githubusercontent.com/assets/6713671/10348014/7db614d8-6d58-11e5-8f44-b894c81c25ff.jpg)

small white rectangle

![bandicam 2015-10-08 01-03-12-332](https://cloud.githubusercontent.com/assets/6713671/10348018/8083fcfc-6d58-11e5-8f13-7c8ea4dd93c2.jpg)

please, keep this place black or dark-gray

**Comment by Alexustas** [comment]
one more thing :)

animation made from "OFF" to "ON", so you may be need to remove  "reverse = true" line from some configs

**Comment by DeputyLOL** [comment]
ok thanks for the help, I'm adding a few basic indicators back in. I'll let you know if they work.

**Comment by DeputyLOL** [comment]
works perfectly! mission accomplished.

**Comment by DeputyLOL** [comment]
wow, hit the wrong button. Didn't even know I could close issues!
Do you want this closed now? Because everything works for me

**Comment by Alexustas** [comment]
Yes, Closed! :-)

**Comment by DeputyLOL** [comment]
On to the next request! :)

**Comment by DeputyLOL** [comment]
I think i found a bug with the warning lights.
If you have a looping sound, it will stop looping if you exit and re-enter IVA.

**Comment by DeputyLOL** [comment]
wait. sorry I'm confused. One of my lights stops looping when i exit. the rest don't.

**Comment by DeputyLOL** [comment]
I found the issue. If a light has a looping sound and no flashing delay, it will stop when you leave IVA.
If it has a flashing delay, it will turn on again when it changes its state.

**Comment by Alexustas** [comment]
i suppose, you need to discuss it with MOARdv

**Comment by DeputyLOL** [comment]
it doesn't happen with the old lights

**Comment by Alexustas** [comment]
give me your cfg, I will try to reproduce the problem

**Comment by Alexustas** [comment]
and describe how the indicator should work

**Comment by DeputyLOL** [comment]
```
MODULE 
{
    name = JSIVariableAnimator      
    refreshRate = 3
    animationName = WL_ONanim
    variableName = CUSTOM_TOOLOWTERRAINALERT
    scale = 0,1
    threshold = 0.5,1.5
    alarmSound = AdvancedCockpit/Sounds/gpws/TooLowTerrain
    alarmSoundVolume = 5
    alarmSoundLooping = true
}
```

**Comment by DeputyLOL** [comment]
I gave you part of it otherwise it would just be confusing.
The alarm turns on when the radar altimeter is decreasing and you are below 1000 feet.
Gear not down flaps up.

The alarm will play and loop and the light will illuminate but when you exit from IVA and then go back, the sound stops even though the light stays on.

**Comment by Alexustas** [comment]
OK. I'll see what I can do

**Comment by Alexustas** [comment]
config for old-style light is the same? difference in the name of animation only ?

**Comment by DeputyLOL** [comment]
Yup

I'm going to be without wifi for a week. I may be able to talk to you at some point but until then I'm putting this on hold until I get back

**Comment by DeputyLOL** [comment]
Just a small comment about the lights, I hadn't noticed until now. It is impossible to click on the korpus collider as it is inside the lamp.

**Comment by Alexustas** [comment]
Now I am engaged in converting my  Parts (ALCOR, ERS...). it will take some time, then I'll deal with Props

**Comment by DeputyLOL** [comment]
Don't worry about this. Its magically fixed itself.
