### ISSUE TITLE
Selector dial

### ISSUE THREAD

**Issue by DeputyLOL** [Alexustas/Props-requests#7]
A new dial for using the numerical input.
![image](https://cloud.githubusercontent.com/assets/12616126/10333794/387d131e-6cde-11e5-867a-d518b78c9f8c.png)

The dial adjusts a numerical value and there is a button (missing in the photo) on the front that 'selects' it. (transfer)

**Comment by Alexustas** [comment]
model

![bandicam 2015-10-08 01-43-14-508](https://cloud.githubusercontent.com/assets/6713671/10348990/157f86fa-6d5e-11e5-913f-4cb67673359c.jpg)

![bandicam 2015-10-08 01-42-49-831](https://cloud.githubusercontent.com/assets/6713671/10348992/1965e584-6d5e-11e5-85ae-83058976c842.jpg)

**Comment by DeputyLOL** [comment]
look cool, does the front have an animated button?

**Comment by Alexustas** [comment]
not yet. but "soon" :-)

**Comment by Alexustas** [comment]
model + texture

![bandicam 2015-10-08 02-59-52-934](https://cloud.githubusercontent.com/assets/6713671/10350945/bd1d8628-6d68-11e5-9472-a9ab4ffe1984.jpg)

**Comment by Alexustas** [comment]
![bandicam 2015-10-08 03-01-19-485](https://cloud.githubusercontent.com/assets/6713671/10350980/eb99ea32-6d68-11e5-8fa7-bbc2624934a6.jpg)

green boxes - "plus" and "minus" colliders

**Comment by Alexustas** [comment]
![bandicam 2015-10-08 03-05-23-332](https://cloud.githubusercontent.com/assets/6713671/10351100/85a19c7e-6d69-11e5-8b60-94097852f8df.jpg)

green sphere - collider for "SEL" button

**Comment by DeputyLOL** [comment]
:D

**Comment by DeputyLOL** [comment]
I have to get some sleep now. Can we continue this tomorrow?

**Comment by Alexustas** [comment]
of course :)

**Comment by Alexustas** [comment]
how mach time in your region now?

**Comment by DeputyLOL** [comment]
its currently 10:20 PM

**Comment by Alexustas** [comment]
02:22 (night) :-)

**Comment by DeputyLOL** [comment]
Back! I got a quiet day today so i'm ready for more modding!

**Comment by Alexustas** [comment]
Hi!

**Comment by Alexustas** [comment]
I'm almost finished Dial prop

**Comment by Alexustas** [comment]
https://youtu.be/jdfLejKZ_Ao

**Comment by DeputyLOL** [comment]
Looks good!

**Comment by Alexustas** [comment]
i think, repeatable "click" sound is needed for press-and-hold action

**Comment by DeputyLOL** [comment]
yeah, agreed.

**Comment by Alexustas** [comment]
can you make a request to MOARdv about looped sound while click and hold?

**Comment by DeputyLOL** [comment]
ok

**Comment by DeputyLOL** [comment]
Issue posted!
If I missed something then you can add to it, or let me know and ill add to it.

**Comment by Alexustas** [comment]
![bandicam 2015-10-08 15-19-16-063](https://cloud.githubusercontent.com/assets/6713671/10362379/1c1ef802-6dd0-11e5-916b-4ad94a27a735.jpg)

Added text labels

**Comment by DeputyLOL** [comment]
:D

**Comment by Alexustas** [comment]
but i never use "transfer" option.

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/jfz0bhymt2d8bji/NumInputDial.zip?dl=0

**Comment by DeputyLOL** [comment]
thanks, testing now

**Comment by DeputyLOL** [comment]
I've got to go for a bit. I'll talk to you later, KSP crashed and I don't have time to reload it now.
I'll talk later.

**Comment by DeputyLOL** [comment]
back again, noticed a slight issue, if the dial is far to one side, it becomes really difficult to click the far side of the dial. What if the colliders were top and bottom instead of left and right?

**Comment by Alexustas** [comment]
you can try it. rotate prop in unity and test.

**Comment by DeputyLOL** [comment]
ok, my computer just BSoD. I'm back now. Back to testing

**Comment by DeputyLOL** [comment]
If I do that then the select button will be sidewise.

**Comment by DeputyLOL** [comment]
I'll try anyway

**Comment by Alexustas** [comment]
i mean rotate what way and test. if it will be better, I redid the model
![bandicam 2015-10-08 18-18-09-932](https://cloud.githubusercontent.com/assets/6713671/10365988/2b89aae4-6de9-11e5-800c-b511f76e407a.jpg)

**Comment by DeputyLOL** [comment]
I know what you meant... :P 
If I do that the select button starts at a weird angle and all the textures round the side are at 90\* as well.

I'll see how it works on its side now my computer has recovered.

**Comment by DeputyLOL** [comment]
Works well on its side, I think it would be better the model was rotated

**Comment by Alexustas** [comment]
well, then I'll put  colliders vertically. "Plus"  above "Minus"

**Comment by DeputyLOL** [comment]
thank you

**Comment by Alexustas** [comment]
what you say about size of colliders?

![bandicam 2015-10-08 18-32-08-809](https://cloud.githubusercontent.com/assets/6713671/10366270/027a6c40-6deb-11e5-84f4-a27d2f758576.jpg)

**Comment by DeputyLOL** [comment]
looks like it will work!

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/jfz0bhymt2d8bji/NumInputDial.zip?dl=0

**Comment by Alexustas** [comment]
just replace existing .mu file

**Comment by DeputyLOL** [comment]
thank you.

**Comment by DeputyLOL** [comment]
testing now

**Comment by DeputyLOL** [comment]
Works Well. I think this is a finished prop! Thank you.
I'll leave it up to you when to close issues unless you want me to?

**Comment by Alexustas** [comment]
I believe this selector is also a part of a EFIS (issue #2 )

**Comment by DeputyLOL** [comment]
wow, I just realised. sorry for the double request.

**Comment by Alexustas** [comment]
it's ok

**Comment by Alexustas** [comment]
whether to further variants of the selector? no buttons on the top or  the other labels?

**Comment by DeputyLOL** [comment]
yes please.
Please could I have 2 more variant with no button.

**Comment by Alexustas** [comment]
i want to make switchable texture for 2nd variant. clean, Course (orange cross), Heading (white triangle) pointer and kind of pointer (gray plastic and white dash)

![knobs](https://cloud.githubusercontent.com/assets/6713671/10374208/b17e7038-6e13-11e5-9e47-7d5f26a1e7dd.jpg)

**Comment by DeputyLOL** [comment]
Yeah, I was kind of thinking that.
I don't know if this is still in this issue but could you make a different model for all of you rotary switches? (2point, 3point 4point)
![image](https://cloud.githubusercontent.com/assets/12616126/10374420/07594b0a-6deb-11e5-84ae-4a158c55105f.png)

**Comment by DeputyLOL** [comment]
Also, this is going to sound odd. A small rotary switch that controls bank. It has 7 points and always defaults to the 4th point (which would be he one in the middle at the top) It can rotate 3 points left or right for 5, 15 and 30 bank and -5, -15 and -30 bank. I know that this probably makes no sense so I'm going to upload a picture in a second

**Comment by DeputyLOL** [comment]
![bank dial](https://cloud.githubusercontent.com/assets/12616126/10374898/89e8588e-6ded-11e5-8e0f-f52705a6cf8e.png)

**Comment by Alexustas** [comment]
start a new issues for all  that props, pls

**Comment by DeputyLOL** [comment]
sure thing

**Comment by Alexustas** [comment]
So,

clear top

![bandicam 2015-10-09 01-34-41-907](https://cloud.githubusercontent.com/assets/6713671/10377642/5aebbc7c-6e26-11e5-9946-95b873f2713f.jpg)

with mark

![bandicam 2015-10-09 01-34-55-223](https://cloud.githubusercontent.com/assets/6713671/10377655/725abd68-6e26-11e5-95f9-3792cac2d230.jpg)

Heading dial

![bandicam 2015-10-09 01-35-18-911](https://cloud.githubusercontent.com/assets/6713671/10377659/78d10fe4-6e26-11e5-95d5-9a35171c5988.jpg)

and Course

![bandicam 2015-10-09 01-35-05-648](https://cloud.githubusercontent.com/assets/6713671/10377663/80709cce-6e26-11e5-8cb6-7dc833727aca.jpg)

**Comment by DeputyLOL** [comment]
Looking Awsome!

**Comment by Alexustas** [comment]
![bandicam 2015-10-09 02-52-02-047](https://cloud.githubusercontent.com/assets/6713671/10379595/eb47173a-6e30-11e5-9068-b39236384c95.jpg)
![bandicam 2015-10-09 02-52-08-213](https://cloud.githubusercontent.com/assets/6713671/10379599/efa6af5c-6e30-11e5-8042-1f9c5f97ac7d.jpg)
![bandicam 2015-10-09 02-52-22-314](https://cloud.githubusercontent.com/assets/6713671/10379608/f35c2a32-6e30-11e5-9fb7-5eb2240cbdf6.jpg)

**Comment by Alexustas** [comment]
https://youtu.be/TJrDsPRSwzE

**Comment by Alexustas** [comment]
DL: https://www.dropbox.com/s/ufg4p5x9naq136w/NumInputDial_NoButton.zip?dl=0

**Comment by Alexustas** [comment]
So,
I've make 7 types of dials and config templates for each of them:
- w/o any pictogram/icons - "clear top"
- Arrow icon
- Course icon
- Dash mark
- Heading icon
- Point mark
- Wide Arrow

Simply open the desired template, edit prop name, NumInput module, perPodPersistent name (in 'JSINumericInput' and 'JSIVariableAnimator' modules)  and re-save it with new name

**Comment by Alexustas** [comment]
If you don't need  backlight, remove "switcher backlight" animator module

**Comment by DeputyLOL** [comment]
Thank you.

**Comment by MOARdV** [comment]
Question on this:

> I've make 7 types of dials and config templates for each of them:

Is it possible to illuminate the pictogram icons (make them emissive)?  In a dark cockpit, the labels are visible, but the icons on the dial are not.

**Comment by Alexustas** [comment]
> Is it possible to illuminate the pictogram icons (make them emissive)? 

of course!

add this module 

```
MODULE
    {
        name = JSICallbackAnimator
        variableName = CUSTOM_ALCOR_BACKLIGHT_ON

        VARIABLESET
        {
            coloredObject = Point_pict //HDG_pict, Arrow_pict, Course_pict, Dash_pict, Point_pict, WideArrow_pict
            passiveColor = 0,0,0,255
            activeColor = 180,180,180,255
            scale = 0.5,1.1
        }
    }
```
